CREATE TABLE [dbo].[Test](
	[Sr No] [float] NULL,
	[ID] [nvarchar](255) NULL,
	[Name] [nvarchar](255) NULL,
	[College] [nvarchar](255) NULL,
	[Course] [nvarchar](255) NULL,
	[Obtained Marks] [float] NULL
) ON [PRIMARY]
GO
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (1, N'ST231165', N'Yeeshu Singh Rajwat', N'GPM', N'Diploma/CS&E', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (2, N'ST231172', N'Verma Shuiesh Kumar', N'GPM', N'Diploma/CS&E', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (3, N'ST231177', N'Anjana Mishra', N'GPU', N'Diloma /CS&E', 21)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (4, N'ST231094', N'Shivani Agarahri ', N'CSJM', N'Diploma/IT', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (5, N'ST231035', N'Shivam Mishra', N'IETA', N'Diploma/IT', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (6, N'ST231069', N'Neetu Gutam', N'GGPA', N'Diploma/IT', 10)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (7, N'ST231278', N'Shreya keshari', N'GGPP', N'Diploma/CS&E', 15)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (8, N'ST231210', N'Khushboo Maurya', N'CSJM', N'Diploma/CS&E', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (9, N'ST231069', N'Shivani  Pal', N'GGPA', N'Diploma/IT', 14)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (10, N'ST231227', N'Utpal Mishra', N'CSJM', N'Diploma/CSE', 15)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (11, N'ST231239', N'Ahmad Farah', N'CSJM', N'Diploma/CSE', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (12, N'ST231240', N'Mohd Sayam Raza', N'CSJM', N'Diploma/CSE', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (13, N'ST231095', N'Avanish Maurya', N'CSJM', N'Diploma/IT', 23)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (14, N'ST231195', N'Anupma Chaudhary', N'CSJM', N'Diploma/CSE', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (15, N'ST231110', N'Khushi Kumari', N'GGPA', N'Diploma/CSE', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (16, N'ST231109', N'Shavani', N'GGPA', N'Diploma/CSE', 10)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (17, N'ST231108', N'Vandana Devi', N'GGPA', N'Diploma/CSE', 15)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (18, N'ST231212', N'Anubhav Agrahari', N'CSJM', N'Diploma/IT', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (19, N'ST231112', N'Priyanshi Srivastav', N'GGPG', N'Diploma/IT', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (20, N'ST231245', N'Ashvani Kumar', N'MJPG', N'Diploma/CSE', 16)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (21, N'ST231113', N'Tansihka Singh', N'GGPG', N'Diploma/IT', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (22, N'ST231229', N'Avinas Tiwari', N'CSJM', N'Diploma/CSE', 21)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (23, N'ST231228', N'Devendra Kumar', N'CSJM', N'Diploma/IT', 21)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (24, N'ST231230', N'Himanshi Pandey', N'CSJM', N'Diploma/CSE', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (25, N'ST231413', N'Mohammad Asif', N'MJPG', N'Diploma/CSE', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (26, N'ST231244', N'Pawan Kumar Gupta', N'MJPG', N'Diploma/CSE', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (27, N'ST231233', N'Akash Kumar', N'CSJM', N'Diploma/IT', 16)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (28, N'ST231232', N'Anshu Ajamil', N'CSJM', N'Diploma/CSE', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (29, N'ST231189', N'Manoj Chaurasiya', N'BIET', N'Btech/IT', 23)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (30, N'ST231100', N'Hariom Kannojia', N'CSJM', N'Diploma/IT', 16)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (31, N'ST231115', N'Suhani Prajapati', N'MJPG', N'Diploma/CSE', 16)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (32, N'ST231155', N'Vibha Yadav\', N'GGPL', N'Diploma/IT', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (33, N'ST231185', N'Krishna Bora', N'FIET Barelly', N'Btech/CS', 21)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (34, N'ST231135', N'Shani Sahu', N'MJPG', N'Diploma/CS', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (35, N'ST231203', N'Amit Kumar', N'GPATG', N'Diploma/CS', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (36, N'ST231179', N'Shivani Singh', N'AIMT LKO', N'Btech/CS', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (37, N'ST231198', N'Akanksa Yadav', N'GGPA', N'Diploma/IT', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (38, N'ST231197', N'Astha Gupta', N'GGPA', N'Diploma/IT', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (39, N'ST231183', N'Sachin Kumar Maurya', N'MMIT', N'Diploma/CS', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (40, N'ST231206', N'Amit Kumar Sahani', N'GP Adampur', N'Diploma/CS', 13)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (41, N'ST231209', N'Vimlesh Pandey', N'GP Adampur', N'Diploma/CS', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (42, N'ST231219', N'Kamini Pal', N'GGPMP', N'Diploma/CS', 12)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (43, N'ST231089', N'Suyash Srivastav', N'MUIT', N'Btech/CS', 16)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (44, N'ST231291', N'Divyanshu Nishad', N'GPATG', N'Diploma/CS', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (45, N'ST231218', N'Neelam Bing', N'GGPMP', N'Diploma/CS', 12)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (46, N'ST231154', N'Devesh Chaturvedi', N'MMIT', N'Diploma/CS', 14)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (47, N'ST231224', N'Aditya Kumar', N'GPS', N'Diploma/CS', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (48, N'ST231234', N'Shveta Dubey', N'CSJM', N'Diploma/CS', 14)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (49, N'ST231111', N'Sneha Saini', N'GGPG', N'Diploma/IT', 14)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (50, N'ST231180', N'Abhishek Singh', N'AIMT LKO', N'Btech/CS', 13)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (51, N'ST231149', N'Ankita Mall', N'KIPM ', N'Btech/CS', 21)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (52, N'ST231157', N'Shivani Pandey', N'GGPL', N'Diploma/IT', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (53, N'ST231163', N'Hiamanshi Prajapati', N'GPU', N'Diploma/CS', 16)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (54, N'ST231141', N'Shalini Mishra', N'CSJM', N'Diploma/CS', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (55, N'ST231187', N'Akash Prajapati', N'GPPP Pratapgarh', N'Diploma/CS', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (56, N'ST231178', N'Payal Awasthi', N'GPU', N'Diploma/CS', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (57, N'ST233181', N'Reena Bharati', N'GPU', N'Diploma/CS', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (58, N'ST231221', N'Radhika Yadav', N'CSJM', N'Diploma/CS', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (59, N'ST231114', N'Prince Singh', N'FIET Barelly', N'Btech/CS', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (60, N'ST231213', N'Sumit Kumar Upadhyay', N'GPATG', N'Diploma/CS', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (61, N'ST231150', N'Shani Dubey', N'MMIT', N'Diploma/CS', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (62, N'ST231220', N'Vishal Patel', N'GGPMP', N'Diploma/CS', 11)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (63, N'ST231144', N'Yogita', N'GGPG', N'Diploma/IT', 15)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (64, N'ST231182', NULL, N'GPPP Pratapgarh', N'Diploma/CS', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (65, N'ST231145', N'Priti Yadav', N'GGPL', N'Diploma/IT', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (66, N'ST231156', N'Rinkee Rawat', N'GGPL', N'Diploma/IT', 14)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (67, N'ST231191', N'Guddu Patel', N'BIETL', N'Diploma/IT', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (68, N'ST231430', N'Anitesh Kumar', N'BIETL', N'Diploma/IT', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (69, N'ST231158', N'Anchal Tripathi', N'CSJM', N'Diploma/CS', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (70, N'ST231127', N'Shalesh Mouraya', N'CSJM', N'Diploma/CS', 14)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (71, N'ST231208', N'Dilshad Alam', N'GPA ', N'Diploma/CS', 10)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (72, N'ST231205', N'Ankit Gupta ', N'GPAG', N'Diploma/CS', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (73, N'ST231207', N'Khurshid Alam', N'GPAG', N'Diploma/CS', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (74, N'ST231295', N'Atal Kumar Yadav', N'GPM', N'DIPLOMA/CS', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (75, N'ST231167', N'Parth Kumar Patel', N'GPM', N'Diploma/CS', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (76, N'ST231166', N'Harshit Sharama ', N'GPM', N'Diploma/CS', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (77, N'ST231120', N'Khushi Lal', N'GPM', N'Diploma/CS', 21)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (78, N'ST231204', N'Gultam Ahmad', N'GPAG', N'Diploma/IT', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (79, N'ST231292', N'Shubham Varma', N'GPAG', N'Diploima/cs', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (80, N'ST231410', N'Vivek  Kumar Gaurav', N'BIET', N'Btech/CS', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (81, N'ST231211', N'Arun Kumar Gautam', N'CSJM', N'Diploma/IT', 21)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (82, N'ST231236', N'Ankit Yadav', N'CSJM', N'Diploma/cs', 19)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (83, N'ST231235', N'Alok Kushawaha', N'CSJM', N'Diploma/IT', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (84, N'ST231148', N'Katayani Singh', N'KIPM ', N'Btech/CS', 22)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (85, N'ST231223', N'Kuldeep Tiwari', N'CSJM', N'Diploma/IT', 16)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (86, N'ST231222', N'Priyanshu', N'CSJM', N'Diploma/CS', 13)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (87, N'ST231422', N'Anand Yadav', N'CSJM', N'Diploma/IT', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (88, N'ST231', N'Jaini Keshrwani', N'MGPGPK', N'Diploma/CS', 17)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (89, N'ST231116', N'Shodha', N'FIET Barelly', N'Btech/CS', 8)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (90, N'ST231090', N'Akash Nishad', N'GPM', N'Diploma', 4)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (91, N'ST231160', N'Ayush Mishra', N'GPU', N'Diploma/CS', 20)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (92, N'ST231266', N'Amardeep Singh', N'GPSPN', N'Diploma/CS', 18)
INSERT [dbo].[Test] ([Sr No], [ID], [Name], [College], [Course], [Obtained Marks]) VALUES (93, N'ST231121', N'Ankit Babu', N'GPM', N'Diploma/CS', NULL)


